port:  5000
markdown: kramdown
name: "My Reps"
url: https://model.earth/my-reps
encoding: utf-8
timezone: America/Chicago
description: "Enter your address to find and contact your federal, state, county and local elected representatives"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyCVxSSf3qiNcQCOVDuBF19ms3rL7b6J_N4
